version: '2'

networks:
  default:
    external:
      name: ${COMPOSE_PROJECT_NAME}

services:
  dss:
    image: dataiku/dss
    container_name: ${COMPOSE_PROJECT_NAME}_dss
    volumes:
      - ./data:/home/dataiku/dss
      - ./requirements.txt:/home/dataiku/requirements.txt
    mem_limit: ${DSS_MEM}
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
    ports:
      - ${PORT}:10000

