version: '3.5'

networks:
  dss-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

services:
# To build custom dataiku_dss image, see docker-compose-build.yml file
#  build_dss:
#    build:
#      context: docker
#    image: ${COMPOSE_PROJECT_NAME:-latelier}_dataiku_dss:${DSS_VERSION:-latest}
#

  design:
    image: ${COMPOSE_PROJECT_NAME:-latelier}_dataiku_dss:${DSS_VERSION:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}_dss_design
    networks:
      - dss-network
    volumes:
       - ${DESIGN_DATA_DIR:-./data-design}:/home/dataiku/dss
       # add custom license
       #- ./license.json:/home/dataiku/license.json
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}
      # add custom license, change install_size
      - DSS_INSTALLER_ARGS=${DESIGN_DSS_INSTALLER_ARGS:- -t design -s auto}
    ports:
      - ${DESIGN_PORT:-10000}:10000

  automation:
    image: ${COMPOSE_PROJECT_NAME:-latelier}_dataiku_dss:${DSS_VERSION:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}_dss_automation
    networks:
      - dss-network
    volumes:
       - ${AUTOMATION_DATA_DIR:-./data-automation}:/home/dataiku/dss
       # add custom license
       #- ./license.json:/home/dataiku/license.json
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}
      # add custom license, change install_size
      - DSS_INSTALLER_ARGS=${AUTOMATION_DSS_INSTALLER_ARGS:- -t automation -s auto}
    ports:
      - ${AUTOMATION_PORT:-10001}:10000

  api:
    image: ${COMPOSE_PROJECT_NAME:-latelier}_dataiku_dss:${DSS_VERSION:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}_dss_api
    networks:
      - dss-network
    volumes:
       - ${API_DATA_DIR:-./data-api}:/home/dataiku/dss
       # add custom license
       #- ./license.json:/home/dataiku/license.json
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}
      # add custom license, change install_size
      - DSS_INSTALLER_ARGS=${API_DSS_INSTALLER_ARGS:- -t api -s auto}
    ports:
      - ${API_PORT:-10002}:10000

  apideployer:
    image: ${COMPOSE_PROJECT_NAME:-latelier}_dataiku_dss:${DSS_VERSION:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}_dss_apideployer
    networks:
      - dss-network
    volumes:
       - ${APIDEPLOYER_DATA_DIR:-./data-apideployer}:/home/dataiku/dss
       # add custom license
       # - ./license.json:/home/dataiku/license.json
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}
      # add custom license, change install_size
      - DSS_INSTALLER_ARGS=${APIDEPLOYER_DSS_INSTALLER_ARGS:- -t apideployer -s auto}
    ports:
      - ${APIDEPLOYER_PORT:-10003}:10000

  dkumonitor:
    image: ${COMPOSE_PROJECT_NAME:-latelier}_dataiku_dkumonitor:${DKUMONITOR_VERSION:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}_dkumonitor
    networks:
      - dss-network
    volumes:
       - ${DKUMONITOR_DATADIR:-./data-dkumonitor}:/home/dkumonitor/data
       # add custom license
       # - ./license.json:/home/dataiku/license.json
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
      - 10003:10003
      - 10004:10004
      - 10005:10005
      - 10006:10006
      - 10007:10007
      - 10008:10008
      - 10009:10009
