version: '2'

networks:
  default:
    external:
      name: ${COMPOSE_PROJECT_NAME}

services:
  dss:
    image: dataiku/dss
    container_name: dss
    volumes:
      - ./data:/home/dataiku/dss
    ports:
      - ${PORT}:10000
    
