version: '2'

networks:
  default:
    external:
      name: latelier

services:
  dss:
    image: dataiku/dss
    container_name: dss
    volumes:
      - ./data:/home/dataiku/dss
      - ./jdbc:/home/dataiku/dss/lib/jdbc
    mem_limit: 12g
    ports:
      - "10000:10000"
    
